### ISSUE TITLE
Generate Certficate for non docker service

### ISSUE THREAD

**Issue by hamon-e** [JrCs/docker-letsencrypt-nginx-proxy-companion#275] opened 2017-11-12 19:05 UTC
Hello,

It would be nice to have a way to generate certificate for services running on host.
(via a configuration file for example)

Thanks

**Comment by buchdag** [comment] 2017-11-19 15:49
Hi,

Can you elaborate on this ? Do you mean for instance generating certificates for apache or nginx running out of docker ?

**Comment by hamon-e** [comment] 2017-11-19 17:36
Today if i want a certficate for a web serveur running on my host, i need to to install a letsencrypt daemon in my host.
I was wondering if it's was possible to add subdomain in a configuration file and mount it to this docker.
(i can't use env variable cause my web server is not in a docker)

**Comment by buchdag** [comment] 2017-11-21 22:38
If you want to create LE certificates without installing an ACME client you can run `simp_le` in a Docker container: https://hub.docker.com/r/zenhack/simp_le/

`simp_le` is the ACME client used by this project.

**Comment by hamon-e** [comment] 2017-11-23 13:02
The point was that i have already have docker-letsencrypt-nginx-proxy-companion running
so i was wondering if it was possible to use it for that kind of case to

**Comment by buchdag** [comment] 2017-11-30 19:04
It's not possible as is (not without doing some super hacky stuff and even then it would be quite limited). I get the idea and agree that it would be handy but I also think it is out of scope. Both this project and `nginx-proxy` are clearly intended for containers and containers only.

**Comment by Panderine** [comment] 2017-12-11 02:39
I'm on the same path. I have a mix of services running as containers and on-host (undockerized). I use nginx-proxy and nginx-le for my containers, but for all my on-host apps this is pain. It would be great to be able to use all the nginx-* suite with those services too since doc-gen, and nginx-proxy / le make this really easy.

**Comment by buchdag** [comment] 2018-02-02 06:21
Duplicate of #127 #220 and #164 

@hamon-e and @Panderine , could take a look at the workaround proposed in #127 ?

**Comment by buchdag** [comment] 2018-06-28 22:43
An **experimental** feature allowing to generate certificates from a config file instead of containers env var (inspired by @ymettier PR #220) has been added to `dev`.

[This instructions are here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta)). Any feedback is welcome.

**Comment by buchdag** [comment] 2018-06-28 22:51
Closing in favor of #386 so we can keep track of this in a single issue.

**Closed by buchdag** 2018-06-28 22:51 UTC
Labels: duplicate, enhancement
