### ISSUE TITLE
Trailing comma causes endless loop

### ISSUE THREAD

**Issue by brainyron** [JrCs/docker-letsencrypt-nginx-proxy-companion#254] opened 2017-08-31 22:26 UTC
If the LETSENCRYPT_HOST variable for a container has a trailing comma, the script does not detect this and attempts to add a certificate for an empty domain name.  This causes simp_le to fail, and the update_certs loop repeats endlessly.

**Comment by buchdag** [comment] 2017-08-31 22:58
I think that can be easily fixed with adjustment to letsencrypt_service_data.tmpl, I'll give it a try tomorrow.

**Comment by buchdag** [comment] 2017-09-01 14:13
My fix worked, but as I suspected the same trailing comma in the `VIRTUAL_HOST` variable cause `nginx-proxy` / `docker-gen` to generate an invalid conf file anyway:

`nginx-proxy    | 2017/09/01 14:06:46 [emerg] 1#1: invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:54`

So there is no point in trying to fix that if the nginx.tmpl isn't fixed first to strip the trailing comma from `VIRTUAL_HOST`.  nginx.tmpl is way more complex than letsencrypt_service_data.tmpl and I'm not good enough with the Go template package to come up with a fix yet.

**Comment by buchdag** [comment] 2017-11-24 13:46
So the issue is fixed for `LETSENCRYPT_HOST` by 4085f64, but since a trailing comma in `VIRTUAL_HOST` will still cause `nginx-proxy` / `docker-gen` to generate an invalid nginx config file, I think using trailing commas should still be avoided for now.

**Closed by buchdag** 2017-11-24 13:46 UTC
Labels: bug
