### ISSUE TITLE
Refused to apply style because the script was loaded even though its MIME type is not a valid JavaScript MIME type

### ISSUE THREAD

**Issue by Sylade** [JrCs/docker-letsencrypt-nginx-proxy-companion#547] opened 2019-06-01 08:05 UTC
Hello,
I make a Identity Server program with Asp.Net Core 2.2 and it works well on http://mydomain.com with the below configuration:

```
  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    container_name: is4
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_PORT: 5000
      VIRTUAL_HOST: my.domain1.com
```

I have a good format on **http**://my.domain1.com
![image](https://user-images.githubusercontent.com/46860984/58745575-deb37b80-8452-11e9-823d-4c5a0e3a08a5.png)

When I apply SSL with your Let's Encrypt docker to this **same** code with the below configuration:
```
  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    container_name: is4
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_PORT: 5000
      VIRTUAL_HOST: my.domain2com
      LETSENCRYPT_HOST: my.domain2.com
      LETSENCRYPT_EMAIL: address@domain2.com
```
I have a formatting problem on **https**://my.donmain2.com:
![image](https://user-images.githubusercontent.com/46860984/58745562-bb88cc00-8452-11e9-9719-ac938e2331b6.png)

In the Firefox web developer:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/46860984/58745631-626d6800-8453-11e9-9350-6331272c669d.png">

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/46860984/58745658-b8421000-8453-11e9-8c6f-7626939cc5c1.png">

<img width="547" alt="image" src="https://user-images.githubusercontent.com/46860984/58745692-5e8e1580-8454-11e9-9981-d09eb0b1b952.png">

What do I have to do to fix this issue?
Thank you.

**Comment by buchdag** [comment] 2019-06-03 16:10
Hi.

Could you please provide your whole configuration (not just the proxyed container, but nginx-proxy or nginx + docker-gen and the companion container) plus containers logs ?

This is likely to ba an issue with `nginx-proxy` as this container (the companion) should not have any effect on the proxying part beside adding the ACME challenge location.

**Comment by Sylade** [comment] 2019-06-03 23:12
Hi,
Thank you for your response.
I use the same configuration from https://chrissainty.com/how-i-dockerised-my-blog/. It is working. I omitted the ghost docker.

nginx-proxy.yml:
```
version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
#    restart: unless-stopped
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /apps/nginx-proxy/files/conf.d:/etc/nginx/conf.d
      - /apps/nginx-proxy/files/vhost.d:/etc/nginx/vhost.d
      - /apps/nginx-proxy/files/html:/usr/share/nginx/html
      - /apps/nginx-proxy/files/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
#    restart: unless-stopped
    restart: always
    volumes:
      - /apps/nginx-proxy/files/conf.d:/etc/nginx/conf.d
      - /apps/nginx-proxy/files/vhost.d:/etc/nginx/vhost.d
      - /apps/nginx-proxy/files/html:/usr/share/nginx/html
      - /apps/nginx-proxy/files/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
#    restart: unless-stopped
    restart: always
    volumes:
      - /apps/nginx-proxy/files/conf.d:/etc/nginx/conf.d
      - /apps/nginx-proxy/files/vhost.d:/etc/nginx/vhost.d
      - /apps/nginx-proxy/files/html:/usr/share/nginx/html
      - /apps/nginx-proxy/files/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

networks:
  default:
    external:
      name: nginx-proxy
```
I use the same structure as this site, nginx, three docker Nginx, nginx-gen & LetsEncrypt are working.


docker logs nginx:
```
51.38.33.18 172.81.240.1 - - [03/Jun/2019:19:59:40 +0000] "GET /w00tw00t.at.blackhats.romanian.anti-sec:) HTTP/1.1" 503 197 "-" "ZmEu"
51.38.33.18 172.81.240.1 - - [03/Jun/2019:19:59:41 +0000] "GET /phpMyAdmin/scripts/setup.php HTTP/1.1" 503 197 "-" "ZmEu"
51.38.33.18 172.81.240.1 - - [03/Jun/2019:19:59:41 +0000] "GET /phpmyadmin/scripts/setup.php HTTP/1.1" 503 197 "-" "ZmEu"
51.38.33.18 172.81.240.1 - - [03/Jun/2019:19:59:42 +0000] "GET /pma/scripts/setup.php HTTP/1.1" 503 197 "-" "ZmEu"
51.38.33.18 172.81.240.1 - - [03/Jun/2019:19:59:42 +0000] "GET /myadmin/scripts/setup.php HTTP/1.1" 503 197 "-" "ZmEu"
51.38.33.18 172.81.240.1 - - [03/Jun/2019:19:59:43 +0000] "GET /MyAdmin/scripts/setup.php HTTP/1.1" 503 197 "-" "ZmEu"
164.132.77.156 54.219.171.20 - - [03/Jun/2019:20:09:18 +0000] "GET / HTTP/1.1" 503 599 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
51.38.33.18 45.174.162.42 - - [03/Jun/2019:21:10:03 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
164.132.77.156 183.94.82.106 - - [03/Jun/2019:21:10:25 +0000] "GET /TP/public/index.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
164.132.77.156 183.93.98.224 - - [03/Jun/2019:21:10:26 +0000] "GET /TP/index.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
164.132.77.156 183.94.82.106 - - [03/Jun/2019:21:10:27 +0000] "GET /thinkphp/html/public/index.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
164.132.77.156 183.93.98.85 - - [03/Jun/2019:21:10:29 +0000] "GET /html/public/index.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
164.132.77.156 183.94.82.50 - - [03/Jun/2019:21:10:31 +0000] "GET /public/index.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
164.132.77.156 183.93.98.166 - - [03/Jun/2019:21:10:40 +0000] "GET /TP/html/public/index.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
51.38.33.18 41.215.13.154 - - [03/Jun/2019:21:10:49 +0000] "GET / HTTP/1.1" 503 599 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
syladebox.com 217.182.4.85 - - [03/Jun/2019:21:13:41 +0000] "GET /wp-login.php HTTP/1.1" 503 197 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
51.38.33.18 87.239.205.112 - - [03/Jun/2019:21:38:37 +0000] "GET /mysql/admin/index.php?lang=en HTTP/1.1" 503 599 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
164.132.77.156 24.151.97.26 - - [03/Jun/2019:21:53:19 +0000] "GET / HTTP/1.1" 503 197 "-" "-"
mbeiw08.myq-see.com 34.246.84.242 - - [03/Jun/2019:21:57:35 +0000] "GET / HTTP/1.1" 503 599 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"
syladebox.com 5.45.207.78 - - [03/Jun/2019:22:04:13 +0000] "GET /robots.txt HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 178.154.244.40 - - [03/Jun/2019:22:04:13 +0000] "GET /robots.txt HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 5.45.207.78 - - [03/Jun/2019:22:04:13 +0000] "GET /robots.txt HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 5.45.207.78 - - [03/Jun/2019:22:04:13 +0000] "GET /robots.txt HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 5.45.207.78 - - [03/Jun/2019:22:04:17 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 178.154.244.40 - - [03/Jun/2019:22:04:17 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 5.45.207.78 - - [03/Jun/2019:22:04:17 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 178.154.244.40 - - [03/Jun/2019:22:04:17 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 37.9.113.113 - - [03/Jun/2019:22:04:21 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 141.8.142.140 - - [03/Jun/2019:22:04:21 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 141.8.142.69 - - [03/Jun/2019:22:04:21 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 141.8.142.140 - - [03/Jun/2019:22:04:21 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 5.45.207.45 - - [03/Jun/2019:22:04:24 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 5.45.207.41 - - [03/Jun/2019:22:04:24 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 5.45.207.45 - - [03/Jun/2019:22:04:25 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
syladebox.com 87.250.224.91 - - [03/Jun/2019:22:04:25 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
www.syladebox.com 180.76.15.148 - - [03/Jun/2019:22:24:36 +0000] "GET / HTTP/1.1" 503 197 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
_ 139.162.178.49 - - [03/Jun/2019:22:31:58 +0000] "GET / HTTP/1.0" 503 197 "-" "-"
_ 14.143.49.170 - - [03/Jun/2019:22:43:49 +0000] "HEAD /robots.txt HTTP/1.0" 503 0 "-" "-"
```


docker logs nginx-gen
```
2019/05/31 22:41:02 Debounce minTimer fired
2019/05/31 22:41:02 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2019/05/31 23:11:33 Received event die for container d461d73bc96c
2019/05/31 23:11:34 Received event stop for container d461d73bc96c
2019/05/31 23:11:39 Debounce minTimer fired
2019/05/31 23:11:39 Generated '/etc/nginx/conf.d/default.conf' from 9 containers
2019/05/31 23:11:39 Sending container 'nginx' signal '1'
2019/05/31 23:11:50 Received signal: hangup
2019/05/31 23:11:50 Received signal: hangup
2019/05/31 23:11:51 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2019/05/31 23:12:37 Received event start for container aaa5056df421
2019/05/31 23:12:42 Debounce minTimer fired
2019/05/31 23:12:42 Generated '/etc/nginx/conf.d/default.conf' from 10 containers
2019/05/31 23:12:42 Sending container 'nginx' signal '1'
2019/05/31 23:12:54 Received signal: hangup
2019/05/31 23:12:54 Received signal: hangup
2019/05/31 23:12:54 Generated '/etc/nginx/conf.d/default.conf' from 10 containers
2019/05/31 23:12:54 Sending container 'nginx' signal '1'
2019/05/31 23:17:38 Received event die for container aaa5056df421
2019/05/31 23:17:40 Received event stop for container aaa5056df421
2019/05/31 23:17:42 Received event start for container 973f735953cc
2019/05/31 23:17:47 Debounce minTimer fired
2019/05/31 23:17:47 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2019/05/31 23:23:07 Received event die for container 973f735953cc
2019/05/31 23:23:08 Received event stop for container 973f735953cc
2019/05/31 23:23:10 Received event start for container c50b0b87cb25
2019/05/31 23:23:15 Debounce minTimer fired
2019/05/31 23:23:15 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2019/06/01 12:43:34 Received event die for container 3f1edf5cfb57
2019/06/01 12:43:35 Received event stop for container 3f1edf5cfb57
2019/06/01 12:43:37 Received event start for container 31048dd97c42
2019/06/01 12:43:42 Debounce minTimer fired
2019/06/01 12:43:42 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
```


docker logs nginx-letsencrypt
```
...
/etc/nginx/certs/ids4.syladebox.com /app
Creating/renewal ids4.syladebox.com certificates... (ids4.syladebox.com)
2019-06-03 20:45:34,010:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
Sleep for 3600s
/etc/nginx/certs/api4.syladebox.com /app
Creating/renewal api4.syladebox.com certificates... (api4.syladebox.com)
2019-06-03 21:45:34,908:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
/etc/nginx/certs/ids4.syladebox.com /app
Creating/renewal ids4.syladebox.com certificates... (ids4.syladebox.com)
2019-06-03 21:45:35,665:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
Sleep for 3600s
/etc/nginx/certs/api4.syladebox.com /app
Creating/renewal api4.syladebox.com certificates... (api4.syladebox.com)
2019-06-03 22:45:36,553:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
/etc/nginx/certs/ids4.syladebox.com /app
Creating/renewal ids4.syladebox.com certificates... (ids4.syladebox.com)
2019-06-03 22:45:37,307:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
Sleep for 3600s
```

My full docker-compose is:
```
version: '3'

services:

  identityserver:
    image: sylade/identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    container_name: is4
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_PORT: 5000
      VIRTUAL_HOST: ids4.syladebox.com
      LETSENCRYPT_HOST: ids4.syladebox.com
      LETSENCRYPT_EMAIL: xxx@gmail.com
  apiservice:
    image: sylade/apiserver
    build:
      context: .
      dockerfile: ApiServer/Dockerfile
    container_name: api
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_PORT: 5001
      VIRTUAL_HOST: api4.syladebox.com
      LETSENCRYPT_HOST: api4.syladebox.com
      LETSENCRYPT_EMAIL: xxxx@gmail.com
      IDENTITY_AUTHORITY: "https://ids4.syladebox.com"
      CLIENT_CORS_ORIGINS: "https://api4.syladebox.com"
  db:
    image: sylade/postgresql:10
    build:
      context: .
      dockerfile: PostgreSQL/Dockerfile10
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /www/database:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
    default:
       external:
         name: nginx-proxy
```

I hope I give to you the good elements.

**Comment by buchdag** [comment] 2019-06-05 05:53
I know the issue happened when you added this container to the mix but this really don't look like a letsencrypt-nginx-proxy-companion issue but rather like a side effect of enabling https.

The only thing the container does is, in order:
- add a location configuration to /.well-known/acme-challenge for your domain on the nginx proxy
- reloads docker-gen and nginx to be sure this change is picked
- get a certficate issued from Let's Encrypt
- put this certificate at the place where docker-gen will expect it
- reload docker-gen so it can find the certificate and generate the new configuration with https enabled and reload nginx

And that's it. This container does not change anything else to the core proxying beside the location configuration for the challenge, and this does not have any bearing on the MIME types returned by your app. Your issue is most probably caused by your own app or by nginx proxy itself.

**Comment by Sylade** [comment] 2019-06-05 17:33
Why does my app work with the Nginx proxy without Let's Encrypt (see the first Dockerfile at the beginning issue)?

**Comment by buchdag** [comment] 2019-06-06 16:05
Could you try to obtain certificates for your two domains through another mean (let say with `certbot`), then enable `nginx-proxy` SSL support by mounting them in the `/etc/nginx/certs` folder as described [here](https://github.com/jwilder/nginx-proxy#ssl-support) and bring your compose stack up **without** the letsencrypt companion ?

If you still have the same issue at this point, that should rule out the involvement of the letsencrypt companion.

**Comment by Sylade** [comment] 2019-06-06 18:32
I don't know some people very well. I will try to do it but how do I de-register my domain certificates? Stopping the letsencrypt companion does not release them before the validation end date.

**Comment by buchdag** [comment] 2019-06-07 08:45
You don't need to, Let's Encrypt will issue a new certificate for your domain(s) whether the previous certificate is still valid or not, as long as the [domain challenge](https://letsencrypt.org/docs/challenge-types/) is validated and you haven't reached [rate limits](https://letsencrypt.org/docs/rate-limits/).

**Comment by Sylade** [comment] 2019-06-09 14:17
OK.
I just noticed in the is4 docker logs that Asp Net Core is working on http://ids.syladebox.com and not http**S**://ids4.syladebox.com:
```
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Request starting HTTP/1.1 GET http://ids4.syladebox.com/ 
```

My code is:
```c
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
            app.UseIdentityServer();
            app.UseCors(builder => builder
                    .AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()//.AllowCredentials()
            );

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        } // Configure()
```

```c
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseUrls("http://*:5000")
                .UseStartup<Startup>();
    }
```

My docker-compose file is in the topic above.

How to enforce HTTPS in Aps Net Core?

**Comment by buchdag** [comment] 2019-06-09 15:02
Providing support for ASP Net Core is way outside the scope of this repo's issues.

Note that you app container not using `https` should not make any difference as the communication between `nginx-proxy` and the proxyed container [happens over `http` by default](https://github.com/jwilder/nginx-proxy#ssl-backends), ie your app container should only see incoming `http` requests from the proxy.

Again I firmly believe that the issue isn't directly caused by `letsencrypt-nginx-proxy-companion` because of [the reasons outlined previously](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/547#issuecomment-498948483). If you have trouble obtaining certificates from Let's Encrypt another way, doing the following will completely remove any influence of the container over `nginx-proxy`:

- stop your `nginx-letsencrypt` container.
- remove the default vhost config file with 
`docker exec nginx rm /etc/nginx/vhost.d/default`
- comment the `nginx-letsencrypt` container out of the compose file.
- bring the compose stack down then up again.

Provided the original certificate you obtained for `ids4.syladebox.com` is still present in the `/etc/nginx/certs` folder, the proxy's `https` configuration will still be enabled.

If your browser does not complain about an invalid certificate (a certificate is either valid or it's not, it won't create MIME related issue) and you still experience the same issue at this point, the issue is not caused by this container.

**Comment by Sylade** [comment] 2019-06-09 15:58
```
docker rm -f nginx-letsencrypt
docker exec nginx rm /etc/nginx/vhost.d/default
```
Comment the nginx-letsencrypt container out of the compose file: 
```
#  nginx-letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: nginx-letsencrypt
##    restart: unless-stopped
#    restart: always
#    volumes:
#      - /apps/nginx-proxy/files/conf.d:/etc/nginx/conf.d
#      - /apps/nginx-proxy/files/vhost.d:/etc/nginx/vhost.d
#      - /apps/nginx-proxy/files/html:/usr/share/nginx/html
#      - /apps/nginx-proxy/files/certs:/etc/nginx/certs:rw
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
#      NGINX_PROXY_CONTAINER: "nginx"
```
```
#docker-compose -f nginx-proxy.yml up -d
nginx-gen is up-to-date
nginx is up-to-date
```

```
#docker exec nginx ls -l /etc/nginx/certs
drwxr-xr-x 3 root root 4096 Dec 13 22:35 accounts
drwxr-xr-x 2 root root 4096 Jun  9 15:30 api4.syladebox.com
lrwxrwxrwx 1 root root   30 Jun  9 15:28 api4.syladebox.com.chain.pem -> ./api4.syladebox.com/chain.pem
lrwxrwxrwx 1 root root   34 Jun  9 15:28 api4.syladebox.com.crt -> ./api4.syladebox.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  9 15:28 api4.syladebox.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   28 Jun  9 15:28 api4.syladebox.com.key -> ./api4.syladebox.com/key.pem
drwxr-xr-x 2 root root 4096 Dec 22 21:59 clt4.syladebox.com
-rw-r--r-- 1 root root 1736 Dec 13 22:16 default.crt
-rw-r--r-- 1 root root 3272 Dec 13 22:16 default.key
-rw-r--r-- 1 root root  424 Dec 13 22:18 dhparam.pem
drwxr-xr-x 3 root root 4096 Jun  9 14:24 https:
drwxr-xr-x 2 root root 4096 Jun  9 15:30 ids4.syladebox.com
lrwxrwxrwx 1 root root   30 Jun  9 15:28 ids4.syladebox.com.chain.pem -> ./ids4.syladebox.com/chain.pem
lrwxrwxrwx 1 root root   34 Jun  9 15:28 ids4.syladebox.com.crt -> ./ids4.syladebox.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  9 15:28 ids4.syladebox.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   28 Jun  9 15:28 ids4.syladebox.com.key -> ./ids4.syladebox.com/key.pem
drwxr-xr-x 2 root root 4096 Jun  9 15:30 syladebox.com
lrwxrwxrwx 1 root root   25 Jun  6 21:43 syladebox.com.chain.pem -> ./syladebox.com/chain.pem
lrwxrwxrwx 1 root root   29 Jun  6 21:43 syladebox.com.crt -> ./syladebox.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  6 21:43 syladebox.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   23 Jun  6 21:43 syladebox.com.key -> ./syladebox.com/key.pem
lrwxrwxrwx 1 root root   25 Jun  6 21:43 www.syladebox.com.chain.pem -> ./syladebox.com/chain.pem
lrwxrwxrwx 1 root root   29 Jun  6 21:43 www.syladebox.com.crt -> ./syladebox.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  6 21:43 www.syladebox.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   23 Jun  6 21:43 www.syladebox.com.key -> ./syladebox.com/key.pem
```

![](https://user-images.githubusercontent.com/46860984/58745562-bb88cc00-8452-11e9-9719-ac938e2331b6.png)

I don't know what to do :(

**Comment by buchdag** [comment] 2019-06-09 16:57
After a few minutes spent on Google it seems that you're far from being the only one having issues when trying to run IdentityServer (or ASP .Net Core itself) behind a proxy.

I really don't know anything about ASP .Net Core but if I where in your shoes I'd start by trying to `curl` one of the problematic file (let say `ids4.syladebox.com/js/site.js`) over both `http` and `https` and check what happens on the `nginx` and `is4` containers logs when you do that. I suggest `curl` because your browser will most probably run into an issue with `http` due to HSTS being used by `nginx-proxy`.

If you want your site to be able through both `http` and `https` at the same time you'll have to set the [`HTTPS_METHOD=noredirect`](https://github.com/jwilder/nginx-proxy#how-ssl-support-works) environment variable on you `docker-gen` container, otherwise requests made to `http` will be redirected to `https`.

I allowed myself to try that just now with `https://ids4.syladebox.com/js/site.js`, and your app just respond with a `404`, so this isn't really a MIME error to begin with. The file just isn't served by your app at all when behind a proxy acting as a TLS termination.

Might have to do with the fact that the proxy <> app communication is `http` only. Or maybe not.

Anyway I'm going to close this issue as this does not concern `letsencrypt-nginx-proxy-companion` directly and I can't really be of any more help to you.

**Closed by buchdag** 2019-06-09 16:57 UTC
Labels: status/more-info-needed

**Comment by buchdag** [comment] 2019-06-09 16:59
IdentityServers's doc recommend reading this when using behind a proxy : https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#scenarios-and-use-cases

**Comment by Sylade** [comment] 2019-06-09 20:01
OK. I can remove the Let's Encrypt problem case. 
Thank you very much for your help. 
I'll keep you informed when the problem is solved.

**Comment by Sylade** [comment] 2019-06-10 14:33
It is solved. 
Before, I used the app publication by FTP.
Now It is necessary to do:

- Push my docker to Docker Hub
- Push it on my server
- Run the Docker compose

=> OK

**Comment by buchdag** [comment] 2019-06-10 14:51
A file permission error then ? Weird.

Well, glad you solved it anyway.

**Comment by Sylade** [comment] 2019-06-10 22:02
Perhaps. 
I had a doubt about a tree structure in /app.
The http site is running on my computer with VisualStudio. The Dockerfiles is:
```
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
#EXPOSE 80
#EXPOSE 443
EXPOSE 5000

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY IS22/IS22.csproj IS22/
RUN dotnet restore IS22/IS22.csproj
COPY . .
WORKDIR /src/IS22
RUN dotnet build IS22.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish IS22.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "IS22.dll"]
```
The directory wwwroot is in /app when I type ```docker exec is4 ls``` :
```
wwwroot/css
wwwroot/js
wwwroot/lib
```

On my server with the letsencrypt-nginx-proxy-companion, Dockerfile is:
```
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
COPY is4/ /app/
WORKDIR /app
ENV ASPNETCORE_URLS http://+:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "IS22.dll"]
```
With it, ```docker exec is4 ls``` gives:
```
css
js
lib
```
It isn't the same tree structure.
The wwwroot directory is missing in /app and the directories css, js, lib are directly in /app.
In the source directory (is4 in the the second line of Dockerfile) I have well:
```
wwwroot/css
wwwroot/js
wwwroot/lib
```
 but after the build Dockerfile I have the bad tree structure...

I read the site https://thomasbandt.com/running-aspnetcore-with-https-in-a-docker-container and
I tested push/pull docker to/from Docker Hub => it is working.
```docker exec is4 ls``` gives now:
```
wwwroot/css
wwwroot/js
wwwroot/lib
```

I deduce that the Dockerfile on my server is not correct.
