### ISSUE TITLE
TOS hash mismatch, cannot create any new certs

### ISSUE THREAD

**Issue by LeoFidjeland** [JrCs/docker-letsencrypt-nginx-proxy-companion#90] opened 2016-08-01 22:27 UTC
This issue in simp_le seems to cause all new cert generation to fail.

https://github.com/kuba/simp_le/issues/114

When it has been fixed, I suppose a new docker image needs to be built?

```
2016-08-01 22:23:40,877:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
TOS hash mismatch. Found: 6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221.
```

Thanks for all the great work!!!

**Comment by thomastweets** [comment] 2016-08-02 09:17
As a workaround: https://hub.docker.com/r/thomastweets/docker-letsencrypt-nginx-proxy-companion/ (see also https://github.com/kuba/simp_le/issues/114)

**Comment by LeoFidjeland** [comment] 2016-08-02 09:21
@thomastweets works perfectly thanks a million!!

**Comment by JrCs** [comment] 2016-08-02 11:09
Update done.

Closed by 7b00e3f

**Closed by JrCs** 2016-08-02 11:09 UTC

**Comment by kachkaev** [comment] 2016-08-03 14:34
Thanks a lot for reacting to this so quickly @JrCs!

Here's the ToS diff (if any one is interested in what they sign):
https://letsencrypt.org/documents/LE-SA-v1.0.1-v1.1.1-diff.docx

More links to letsencrypt documents:
https://letsencrypt.org/repository/

**Comment by magnontobi** [comment] 2016-08-09 18:59
Am I the only one who's still getting this?

**Comment by faultylee** [comment] 2016-08-10 00:31
I was seeing the same message yesterday when I was adding a new host, though the cert generated properly. I guess it's non fatal since it's "INFO".

**Comment by JrCs** [comment] 2016-08-10 06:22
It must work now with the new version

**Comment by magnontobi** [comment] 2016-08-10 13:19
After countless of seemingly hopeless attempts to get this working, it somehow fixed itself after a (second) reboot of the host and all the containers.

**Comment by peXed** [comment] 2016-09-23 07:35
Hello!
Is the problem back again? Will the issue come always after an TOS change?

I get the error:
`TOS hash mismatch. Found: 6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221.
`
This is with a fresh image.

**Comment by paolomainardi** [comment] 2016-10-04 16:52
Same problem here.

**Comment by 1beb** [comment] 2016-10-19 22:08
Same problem here. Will report back after update/reboot.

**Comment by fradeve** [comment] 2017-11-16 12:39
I'm using `image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'` and I still get this.

**Comment by mlaitinen** [comment] 2017-11-16 12:50
Same here. @fradeve I got this working by setting an environment variable `ACME_TOS_HASH` to value `cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b`. Don't know if this is a kosher solution.

**Comment by fradeve** [comment] 2017-11-16 13:06
That fixed it! Amazing, thanks :)

**Comment by rgruesbeck** [comment] 2017-11-16 17:47
Same here.

**Comment by bfayers** [comment] 2017-11-16 17:59
Once this is patched into the image, what's the easy way of updating the container without data loss?

**Comment by bfayers** [comment] 2017-11-16 18:02
@mlaitinen Where am i supposed to set this envvar?

**Comment by buchdag** [comment] 2017-11-16 18:04
@bfayers on the `letsencrypt-nginx-proxy-companion` container

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#optional-container-environment-variables

**Comment by bfayers** [comment] 2017-11-16 18:05
I got it :)

**Comment by krystalcode** [comment] 2017-11-18 16:45
Where can we be getting the latest hash? It seems to have changed again ...

`TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.`

**Comment by buchdag** [comment] 2017-11-18 16:47
@krystalcode #277 #282

**Comment by xandermar** [comment] 2017-12-02 15:29
I can confirm that using the latest version (as of 2 DEC 2017) solves the TOS issue. I stopped/deleted my Letsencrypt container and image. I ran 'docker-compose up -d' pulling the latest image and the problem went away.

**Comment by herejia** [comment] 2017-12-31 15:49
As of e47e065463db I just ran `docker rm my-container-name` and `docker pull jrcs/letsencrypt-nginx-proxy-companion` and everything went fine

**Comment by pattonwebz** [comment] 2018-03-01 02:24
I am unsure how long this has been a problem in my containers but I ran into it today adding a new container.

Getting latest image as of today fixes it for me.

**Comment by dblock** [comment] 2018-03-29 22:06
`dokku plugin:update letsencrypt` is probably the better first thing to try, no? With 0.8.8 I got past that error but hit https://github.com/dokku/dokku-letsencrypt/issues/149.
