### ISSUE TITLE
Container restart drops any custom certificates

### ISSUE THREAD

**Issue by StalkAlex** [JrCs/docker-letsencrypt-nginx-proxy-companion#351] opened 2018-03-19 18:24 UTC
Thanks for that handy tool!

I'm using this companion with jwilder/nginx-proxy. I have two domains for my application. For one of them I want let's encrypt certifcates, but for another I have got already valid certificates, so I just placed them in the same folder where companion placing generated ones. 
Everything works fine until container restart, after restart let's encrypt certificates are still there but custom certificates are gone. 

Is there any workaround for this problem?

**Comment by buchdag** [comment] 2018-03-19 18:45
Sorry for the regression, I identified the reason, that should be fixed on `dev`, could you pull `jrcs/letsencrypt-nginx-proxy-companion:dev` and try it ?

**Comment by StalkAlex** [comment] 2018-03-19 18:47
@buchdag I'll try tomorrow and let you know.

**Comment by StalkAlex** [comment] 2018-03-19 18:53
On second thought, decided to check now and it's working now as expected. Thanks, no unexpected removals.

**Comment by buchdag** [comment] 2018-03-19 18:56
Thanks for the fix confirmation. The fixed version has been pushed as `latest` and `v1.8` too to prevent this regression from affecting further people.

**Comment by buchdag** [comment] 2018-03-19 20:16
Fixed by #352

**Closed by buchdag** 2018-03-19 20:16 UTC
Labels: bug
