### ISSUE TITLE
Cannot authorize any certs

### ISSUE THREAD

**Issue by joeknock90** [JrCs/docker-letsencrypt-nginx-proxy-companion#128] opened 2016-12-02 02:19 UTC
I had this working PERFECTLY until I rebuilt my docker server recently. 

Every container will not get a valid certificate. I'm currently using jwilder's nginx-proxy all in one container, but I have tried the separate official nginx and jwilder/docker-gen. I am having the same issue every time. 

I am currently built this way: 

jwilder/nginx-proxy:

`docker run -d -p 80:80 -p 443:443 --restart=always \
    --name nginx-proxy \
    -v /etc/nginx/certs:/etc/nginx/certs:ro \
    -v /etc/nginx/vhost.d:/etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy`

then this container:

`docker run -d --restart always --name nginx_certs \
    -v /etc/nginx/certs:/etc/nginx/certs:rw \
    --volumes-from nginx-proxy \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    jrcs/letsencrypt-nginx-proxy-companion`

EVERY SINGLE TIME.... I get this in the logs of the companion container:

`2016/12/02 01:42:22 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
R2016/12/02 01:42:22 Generated '/etc/nginx/conf.d/default.conf' from 10 containers
;2016/12/02 01:42:22 [notice] 42#42: signal process started
Creating/renewal app.imnottellingyoumydomain.tld certificates... (app.imnotellingyoumydomain.tld)
2016-12-02 01:42:23,283:INFO:simp_le:1211: Generating new account key
2016-12-02 01:42:23,909:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:24,087:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:24,374:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:24,774:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
2016-12-02 01:42:25,509:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:25,754:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:26,181:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): app.imnottellingyoumydomain.tld
2016-12-02 01:42:26,251:INFO:simp_le:1305: app.imnottellingyoumydomain.tld was successfully self-verified
2016-12-02 01:42:26,270:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:26,479:INFO:simp_le:1313: Generating new certificate private key
2016-12-02 01:42:28,029:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:32,298:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-02 01:42:32,582:ERROR:simp_le:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/G-dC_gRcT5QWJjhbMDCtbrM0GBEHsQUd3o2BtBJ3ik0
Challenge validation has failed, see error log.
Debugging tips: -v improves output verbosity. Help is available under --help.`

I am using both 
`VIRTUAL_HOST=app.imnottellingyoumydomain.tld`
and 
`LETSENCRYPT_HOST=app.imnottellingyoumydomain.tld`
and
`LETSENCRYPT_EMAIL=youcanguessmyname@imnottellingyoumydomain.tld`

Of course all of my domain and dns are set up correctly. Self signed certificates work fine. 

Someone PLEASE.

**Comment by amlwwalker** [comment] 2016-12-07 13:41
same issue

**Comment by joeknock90** [comment] 2016-12-07 16:08
Is this project abandoned?

**Comment by thatbudakguy** [comment] 2016-12-12 20:03
same issue, using fix from #130

**Comment by weaktyper** [comment] 2016-12-12 20:08
This is not the same issue as #130. The exception is different.

**Comment by thatbudakguy** [comment] 2016-12-12 20:14
@weaktyper right - just thought it worth mentioning that I could replicate this issue on the docker image that is provided in discussion of #130 as well as the default docker image.

**Comment by weaktyper** [comment] 2016-12-12 20:22
@thatbudakguy Ok, I thought you meant it was the same issue, you are having the same issue. [Issue 107](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/107) seems quite similar to this one. In fact this could be a duplicate of #107.

**Comment by joeknock90** [comment] 2016-12-12 20:29
I was unable to get it working with any of the posted .tmpl files. I've tried basically all of them and scoured for even older ones. If you have a suggestion on one I would be happy to give it a shot just to reduce clutter in the bug reports.

**Comment by weaktyper** [comment] 2016-12-12 21:05
@joeknock90  Not so sure what template to use. If I have time some day I might have a look..

**Comment by amlwwalker** [comment] 2016-12-13 11:56
As far as I can tell the webroot method is the issue.
I can't see how the endpoints are meant to be generated so that letsencrypt can callback to the .well-known endpoint on my server for each container that needs a certificate.
I know that letsencrypt has an "nginx" mode which may be useful for this, and as others seem to be having issues, perhaps someone can outline what should happen, or whether moving to the nginx method is better?

**Comment by gtrias** [comment] 2016-12-14 14:55
I'm having exact same problem. I'm using the forked image from #130 which fixes the Deserialization error, but now I cannot renew any certificate getting the same errors from this issue... It used to work before I'm not sure if it's related with #130 fix.

**Comment by Braintelligence** [comment] 2016-12-16 16:21
Same issue, also using the #130 fix.

**Comment by alastaircoote** [comment] 2016-12-20 19:41
@Braintelligence no, I don't get this issue at all, sorry. Not sure what the cause is.

**Comment by Rid** [comment] 2016-12-22 03:18
Can you try this https://hub.docker.com/r/riid/docker-gen-multi ?

**Comment by joeknock90** [comment] 2017-01-05 19:58
Does anyone have any idea what this could be?

I cannot get this to work for the life of me. It worked fine 2 months ago. Ever since I rebuild my server it will never authorize the certs. 

DNS works fine, and I can access everything fine via HTTP. 

As soon as I try to generate certs, nothing...

**Comment by royalaid** [comment] 2017-01-08 22:44
@Rid Thank you for the fix, the certs are finally working again.

**Comment by kosli** [comment] 2017-01-09 17:42
@JrCs are you going to use that fix too?

**Comment by kosli** [comment] 2017-01-13 10:02
@Rid just replacing the two images doesn't work for me, I get the following error:

> letsencrypt-nginx-proxy-companion[999]: 2017/01/13 11:00:13 Error creating generator: Bad endpoint: Invalid bind address format: -watch 
> letsencrypt-nginx-proxy-companion[999]: /app/start.sh: line 5: kill: (28) - No such process 

is the rest of the instruction from JrCs's version the same? e.g. i am using docker compose (v1)

**Comment by Rid** [comment] 2017-01-13 10:50
@kosli try now please

**Comment by kosli** [comment] 2017-01-13 11:11
@rid now it seems to be another problem?
nginx-gen                            | Usage: docker-gen [options] template [dest]
nginx-gen                            |
nginx-gen                            | Generate files from docker container meta-data
etc.....

i changed the container names to be nginx, nginx-letsencrypt, nginx-gen as i thought this may be an issue too... but didn't help.

**Comment by kosli** [comment] 2017-01-17 21:14
it seems that somehow the certificates got renewed with the original version from jrcs.

**Comment by JrCs** [comment] 2017-01-20 12:00
Is it working now for all and my latest container version ?

**Comment by kosli** [comment] 2017-01-20 13:20
@JrCs for me it works with the version from @Rid 
have you merged his changes into your version? i could test on another host where some certs will need to be renewed soon.

**Comment by joeknock90** [comment] 2017-01-20 14:56
Sorry, just got off a vacation:

@JrCs I just switched to a new hosting provider and now am running your latest container version. It is working. Not sure what the problem was before but those machines are gone.

**Closed** 2017-01-20 14:57 UTC
Labels: status/more-info-needed

**Comment by dasmaeh** [comment] 2017-02-10 21:58
Still not working for me. I and letsencrypt are always getting an error 404 on mydomain.tld/.well-known/acme-challenge/

Only error message is as in the original issue.
Any ideas what could be the reason?
