### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by offbeatful** [JrCs/docker-letsencrypt-nginx-proxy-companion#488] opened 2018-12-29 23:57 UTC
I get the following error during certificate generation:

```
Creating/renewal st.example.com certificates... (st.example.com)
2018-12-29 23:48:14,336:INFO:simp_le:1479: Generating new certificate private key
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1483, in persist_new_data
    certr = get_certr(client, csr, authorizations)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1425, in get_certr
    ', '.join(authzr.uri for _, authzr in error.exhausted)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1425, in <genexpr>
    ', '.join(authzr.uri for _, authzr in error.exhausted)
ValueError: too many values to unpack
```

**Background:**

Configuration is pretty standard:

```yaml
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - gateway_network

  dockergen:
    build:      
      context: ./dockergen
    container_name: dockergen
    restart: unless-stopped
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro      
      - nginx_conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - gateway_network

  letsencrypt-companion:
    restart: unless-stopped
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=dockergen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - gateway_network

networks:
  gateway_network:
    name: gateway_network  

volumes:
    nginx_conf:
    nginx_html:
    vhost:
    certs:      
    
```

There are 6 websites total. I get certificates generated for 4 of them successfully. But I get this aforementioned error for other two.
If I understand correctly from the error it fails to unpack some error response values. How can I see what was the error? Is there request/response logs?

Can it be a rate limiting issue?

**Comment by h44z** [comment] 2019-01-02 19:42
I get the same error here using the evertramos/docker-compose-letsencrypt-nginx-proxy-companion image.

**Comment by buchdag** [comment] 2019-01-04 14:18
@offbeatful : the simp_le traceback seems to indicate that you are using an outdated version of the container.

@h44z : we don't provide support for forks of this project.

**Comment by offbeatful** [comment] 2019-01-06 16:31
@buchdag is v1.9.1 latest? I tried many couple of versions - still the same issue.

A side note: changing to staging didn't solve the problem. But when I restarted docker host - everything starts magically work. I assume that there are some connectivity issues and was not properly handled by the lib.

**Comment by h44z** [comment] 2019-01-06 18:47
I solved the issue on my side, the problem was, that the container was not reachable via IPv6, so the validation timed out. It seems that the timeout response does not get parsed correctly, thats why we get this error.

**Comment by buchdag** [comment] 2019-01-07 09:13
This looks similar to #397

**Comment by dr4y** [comment] 2019-01-07 14:36
Yes but I do not have any :ro despite of the docker socket similar to @offbeatful up there.

**Comment by buchdag** [comment] 2019-01-09 21:36
My take on this issue is that the standalone `docker-gen` container cause the authorization to fail for some reason and then `simp_le` is unable to process this specific answer from the ACME CA. That's only a guess from the fact that taking the `docker-gen` container out of the equation seems to solve the issue. I'm still unable to reproduce it.

What OS are you using with which docker version ? Is everything up to date (containers, docker-compose, nginx.tmpl, etc) ?

@offbeatful I see that your are building the `docker-gen` container, could you share the Dockerfile you are using ?

**Comment by buchdag** [comment] 2019-02-11 13:19
Looks like `simp_le` is having a hard time handling network related issues, I'm not sure there is much we can do from the `letsencrypt-nginx-proxy-companion` container perspective.

**Comment by buchdag** [comment] 2019-03-12 15:31
As this is most probably a `simp_le` issue that we can't fix from our end, I'm going to close this issue for now. Feel free to re-open it if needed.

**Closed by buchdag** 2019-03-12 15:31 UTC
