### ISSUE TITLE
Support for static reverse proxying with SSL

### ISSUE THREAD

**Issue by mossholderm** [JrCs/docker-letsencrypt-nginx-proxy-companion#164] opened 2017-02-08 15:22 UTC
Add support for proxy destinations that are "off-box" and not in docker containers. For example, It would be great to be able to have an encrypted connection land on the nginx-proxy docker container, and then travel unencrypted to the destination server (which isn't a container).

nginx-proxy supports adding a configuration file to achieve this end, but nginx-letsencrypt has no method to handle generating/managing the certificates for this sort of situation.

Perhaps permit allowing some environment variables for passing in additional hostnames/emails for certificates that should be managed, regardless of container existence?

**Comment by ryneeverett** [comment] 2017-02-09 01:07
Dupe of #127, though that one was arguably never resolved.

**Comment by ForsakenHarmony** [comment] 2017-02-13 01:54
Yeah, only a workaround, would be interested in this

**Comment by JrCs** [comment] 2017-02-13 17:53
The best is perhaps to use another solution like [traefik](https://traefik.io)

**Comment by augusteo** [comment] 2017-04-16 12:11
if you are still having problem with it, I solved it by using another nginx container to serve the static directory, like so:

```yaml
# other lines

static-main-site:
     restart: always
     image: nginx:alpine
     volumes:
       - ./static/path:/usr/share/nginx/html:ro
     environment:
       - VIRTUAL_HOST=www.domain.com,domain.com
       - VIRTUAL_NETWORK=nginx-proxy
       - VIRTUAL_PORT=80
       - LETSENCRYPT_HOST=www.domain.com,domain.com
       - LETSENCRYPT_EMAIL=mail@gmail.com
```

**Comment by Pimmetje** [comment] 2017-07-16 17:23
I would love to be able to put some config somewhere for a reverse https proxy with letsencrypt SSL. This would also work if u for some reason don't want to use docker socket.

**Comment by buchdag** [comment] 2018-06-28 22:52
An **experimental** feature allowing to generate certificates from a config file instead of containers env var (inspired by @ymettier PR #220) has been added to `dev`.

[This instructions are here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta)). Any feedback is welcome.

Closing in favor of #386 so we can keep track of this in a single issue.

**Closed by buchdag** 2018-06-28 22:52 UTC
Labels: duplicate, enhancement
