### ISSUE TITLE
unable to generate certs for second proxy

### ISSUE THREAD

**Issue by rebrube** [JrCs/docker-letsencrypt-nginx-proxy-companion#171] opened 2017-02-15 10:42 UTC
I'm trying to run the jwilder/nginx-proxy twice, each with it's own dedicated IP.
For 'reasons' I cannot have the domains of proxy1 in the certificate of proxy2.
I modified the jwilder/nginx-proxy to look for VIRTUAL_HOSTS instead of VIRTUAL_HOST and run it as proxy2.
This set-up seems to work without issue.
The docker run for proxy1 looks as follows:
> docker run -d -p ip.proxy.1:80:80 -p ip.proxy.1:443:443 --network isolated --name proxy \
>       -v /home/user/conf/htpasswd:/etc/nginx/htpasswd \
>       -v /home/user/certs:/etc/nginx/certs:ro -v /etc/nginx/vhost.d \
>       -v /home/user/conf/proxy1/cust.conf:/etc/nginx/conf.d/my_proxy.conf:ro \
>       -v /usr/share/nginx/html -v /var/run/docker.sock:/tmp/docker.sock:ro \
>       -v /home/user/logs/proxy/:/var/log/nginx/:rw jwilder/nginx-proxy

the docker run for proxy2 looks as follows:
> docker run -d -p proxy.ip.2:80:80 -p proxy.ip.2:443:443 --network isolated --name proxy2 \
>       -v /home/user/certs:/etc/nginx/certs:ro -v /etc/nginx/vhost.d\
>       -v /usr/share/nginx/html -v /var/run/docker.sock:/tmp/docker.sock:ro \
>       -v /home/user/logs/proxy2/:/var/log/nginx/:rw proxy2

The docker run for the letsencrypt companion looks as follows:
> docker run -d \
>    --name ssl \
>    -v /home/user/certs:/etc/nginx/certs:rw \
>    --network isolated \
>    --volumes-from proxy \
>    --volumes-from proxy2 \
>    -v /var/run/docker.sock:/var/run/docker.sock:ro \
>    jrcs/letsencrypt-nginx-proxy-companion

I notice the 2nd proxy passes the .well-known request to the upstream.
In the upstream logs I get:
> 172.17.0.8 - - [15/Feb/2017:10:12:30 +0000] "GET /.well-known/acme-challenge/Umzbul_challenge_Mzb5v8E0Uk-ydRc HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "letsencrypt.ip"

in the proxy2 logs I get:
> example.com letsencrypt.ip - - [15/Feb/2017:10:12:30 +0000] "GET /.well-known/acme-challenge/Umzbul_challenge_Mzb5v8E0Uk-ydRc HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"

in the letsencrypt companion I get:
> 2017-02-15 10:12:30,075:ERROR:acme.challenges:256: Unable to reach http://example.com/.well-known/acme-challenge/Umzbul_challenge_Mzb5v8E0Uk-ydRc: HTTPConnectionPool(host='example.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/Umzbul_challenge_Mzb5v8E0Uk-ydRc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f1d056d9250>: Failed to establish a new connection: [Errno 113] Host is unreachable',))
> 2017-02-15 10:12:30,075:WARNING:simp_le:1303: example.com was not successfully self-verified. CA is likely to fail as well!

Is the letsencrypt companion able to serve 2 nginx-proxies or should I run it twice with some modifications?

**Comment by dschroe** [comment] 2017-07-25 11:35
Do you have any solution yet?

**Comment by buchdag** [comment] 2018-02-01 21:32
Duplicate of #242 so closing to have only one issue tracking this.

**Closed by buchdag** 2018-02-01 21:32 UTC
